# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-26 18:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Effects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='名称', max_length=255, verbose_name='名称')),
                ('level', models.IntegerField(choices=[('1', '级别一'), ('2', '级别二'), ('3', '级别三')], default='1', help_text='级别', verbose_name='级别')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('parent', models.ForeignKey(blank=True, help_text='上级id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='resoucedit.Effects', verbose_name='上级id')),
            ],
            options={
                'verbose_name': '特效管理',
                'verbose_name_plural': '特效管理',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='名称', max_length=255, verbose_name='名称')),
                ('mp3', models.FileField(help_text='音乐地址', upload_to='mp3/%Y/%m/%d/', verbose_name='音乐地址')),
                ('level', models.IntegerField(choices=[('1', '级别一'), ('2', '级别二'), ('3', '级别三')], default='1', help_text='级别', verbose_name='级别')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('parent', models.ForeignKey(blank=True, help_text='上级id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='resoucedit.Music', verbose_name='上级id')),
            ],
            options={
                'verbose_name': '音乐管理',
                'verbose_name_plural': '音乐管理',
            },
        ),
    ]
