# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-26 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoucedit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effects',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='music',
            name='parent',
        ),
        migrations.AlterField(
            model_name='effects',
            name='level',
            field=models.IntegerField(choices=[(1, '热门'), (2, '夏日选集'), (3, '促销选集'), (4, '图形选集'), (5, '自然选集'), (6, '节庆选集')], default=1, help_text='类别', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='music',
            name='level',
            field=models.IntegerField(choices=[(1, '热门'), (2, '网络歌曲'), (3, '节日'), (4, '古典'), (5, '钢琴'), (6, '儿童'), (7, '自然')], default=1, help_text='类别', verbose_name='类别'),
        ),
    ]
