# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-27 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resoucedit', '0003_brandcateimages_titles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandcateimages',
            options={'verbose_name': '品牌分类图片', 'verbose_name_plural': '品牌分类图片'},
        ),
        migrations.AlterModelOptions(
            name='titles',
            options={'verbose_name': '标题', 'verbose_name_plural': '标题'},
        ),
    ]
