# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 14:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cate', '0004_auto_20190225_1524'),
        ('resoucedit', '0004_auto_20190227_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAttrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='名称', max_length=255, verbose_name='名称')),
                ('value', models.ImageField(default='', help_text='值', max_length=255, upload_to='', verbose_name='值')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('cate', models.ForeignKey(blank=True, help_text='分类id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_cates', to='cate.Cates', verbose_name='分类id')),
            ],
            options={
                'verbose_name': '案例属性',
                'verbose_name_plural': '案例属性',
            },
        ),
    ]
