# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoucedit', '0005_caseattrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseattrs',
            name='value',
            field=models.CharField(default='', help_text='值', max_length=255, verbose_name='值'),
        ),
    ]
