# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190313_2042'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='goodsinfo',
        ),
    ]
