# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoucedit', '0006_auto_20190304_1407'),
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acts',
            name='attrs',
            field=models.ManyToManyField(blank=True, help_text='属性列表', null=True, to='resoucedit.CaseAttrs', verbose_name='属性列表'),
        ),
    ]
