# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_acts_attrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acts',
            name='attrs',
            field=models.ManyToManyField(help_text='属性列表', to='resoucedit.CaseAttrs', verbose_name='属性列表'),
        ),
    ]
