# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cate', '0004_auto_20190225_1524'),
        ('case', '0003_auto_20190304_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='acts',
            name='cate',
            field=models.ForeignKey(blank=True, help_text='分类id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_cate', to='cate.Cates', verbose_name='分类id'),
        ),
    ]
