# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_casebrands_casefavo_casesigns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acts',
            options={'verbose_name': '案例', 'verbose_name_plural': '案例'},
        ),
        migrations.AlterModelOptions(
            name='casebrands',
            options={'verbose_name': '门店字段', 'verbose_name_plural': '门店字段'},
        ),
        migrations.AlterModelOptions(
            name='casefavo',
            options={'verbose_name': '优惠字段', 'verbose_name_plural': '优惠字段'},
        ),
        migrations.AlterModelOptions(
            name='casesigns',
            options={'verbose_name': '报名字段', 'verbose_name_plural': '报名字段'},
        ),
    ]
