# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-07 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_auto_20190306_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acts',
            name='image',
            field=models.ImageField(blank=True, help_text='单张图', null=True, upload_to='actimage/%Y/%m/%d/', verbose_name='单张图'),
        ),
    ]
