# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 11:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('xj', '请选择所属行业'), ('jypx', '教育培训'), ('cyms', '餐饮美食'), ('xfgw', '消费购物'), ('shfw', '生活服务'), ('xxyl', '休闲娱乐'), ('mrmf', '美容美发'), ('hqyl', '婚庆影楼'), ('ydjs', '运动健身'), ('qcmr', '汽车美容'), ('jzsj', '家装设计'), ('lyjq', '旅游景区'), ('qt', '其他')], default='xj', max_length=20, verbose_name='行业')),
                ('qustion', models.CharField(choices=[('q0', '请选择要解决的问题'), ('q1', '节日到了，营销怎么搞?'), ('q2', '想做老带新，没思路?'), ('q3', '周边竞争大，如何打造特色?'), ('q4', '门店位置偏，如何拓客?'), ('q5', '没有本地资源，如何推广?'), ('q6', '不想降价促销，怎么做活动?'), ('q7', '新店开业怎么拓新客?'), ('q8', '周年庆活动应该怎么做?'), ('q9', '异业合作该如何开展?'), ('q10', '模板眼花缭乱，究竟哪款适合自己?'), ('q11', '其他')], default='q0', max_length=200, verbose_name='问题')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商家',
                'verbose_name_plural': '商家',
            },
        ),
        migrations.CreateModel(
            name='China',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='名称', max_length=30, verbose_name='名称')),
                ('parent', models.ForeignKey(blank=True, help_text='上级id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='users.China', verbose_name='上级id')),
            ],
            options={
                'verbose_name': '中国城市',
                'verbose_name_plural': '中国城市',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_sj',
            field=models.BooleanField(default=False, verbose_name='是否商家'),
        ),
        migrations.AddField(
            model_name='business',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.China', verbose_name='省/市/县或区'),
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
