# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190220_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='china',
            name='level',
            field=models.IntegerField(default=2, help_text='层级', verbose_name='层级'),
        ),
    ]
