# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_china_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='china',
            name='parent',
            field=models.IntegerField(blank=True, help_text='上级id', null=True, verbose_name='上级id'),
        ),
    ]
