# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 16:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190220_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='business',
            name='industry',
            field=models.CharField(choices=[('xj', '请选择所属行业'), ('jypx', '教育培训'), ('cyms', '餐饮美食'), ('xfgw', '消费购物'), ('shfw', '生活服务'), ('xxyl', '休闲娱乐'), ('mrmf', '美容美发'), ('hqyl', '婚庆影楼'), ('ydjs', '运动健身'), ('qcmr', '汽车美容'), ('jzsj', '家装设计'), ('lyjq', '旅游景区'), ('qt', '其他')], default='xj', help_text='行业', max_length=20, verbose_name='行业'),
        ),
        migrations.AlterField(
            model_name='business',
            name='part',
            field=models.ForeignKey(help_text='省/市/县或区', on_delete=django.db.models.deletion.CASCADE, to='users.China', verbose_name='省/市/县或区'),
        ),
        migrations.AlterField(
            model_name='business',
            name='qustion',
            field=models.CharField(choices=[('q0', '请选择要解决的问题'), ('q1', '节日到了，营销怎么搞?'), ('q2', '想做老带新，没思路?'), ('q3', '周边竞争大，如何打造特色?'), ('q4', '门店位置偏，如何拓客?'), ('q5', '没有本地资源，如何推广?'), ('q6', '不想降价促销，怎么做活动?'), ('q7', '新店开业怎么拓新客?'), ('q8', '周年庆活动应该怎么做?'), ('q9', '异业合作该如何开展?'), ('q10', '模板眼花缭乱，究竟哪款适合自己?'), ('q11', '其他')], default='q0', help_text='问题', max_length=200, verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(default='', help_text='地区', max_length=20, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', help_text='邮箱', max_length=20, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_sj',
            field=models.BooleanField(default=False, help_text='是否商家', verbose_name='是否商家'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(default='', help_text='手机', max_length=11, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', help_text='性别', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wename',
            field=models.CharField(default='', help_text='微信用户昵称', max_length=20, verbose_name='微信用户昵称'),
        ),
    ]
