# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190220_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='businame',
            field=models.CharField(default='', help_text='机构名称', max_length=255, verbose_name='机构名称'),
        ),
    ]
