# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_business_businame'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='status',
            field=models.IntegerField(default=0, help_text='是否审核', verbose_name='是否审核'),
        ),
    ]
