# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-21 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_business_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.BooleanField(default=False, help_text='是否审核', verbose_name='是否审核'),
        ),
    ]
