# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-21 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190221_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='part',
            field=models.ForeignKey(default=110000, help_text='省/市/县或区', on_delete=django.db.models.deletion.CASCADE, to='users.China', verbose_name='省/市/县或区'),
        ),
    ]
