# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-24 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190221_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='industry',
            field=models.CharField(default='1', help_text='行业', max_length=20, verbose_name='行业'),
        ),
    ]
