# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190224_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='weimage',
            field=models.CharField(default='', help_text='微信用户头像', max_length=255, verbose_name='微信用户头像'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weopenid',
            field=models.CharField(default='', help_text='微信openid', max_length=50, verbose_name='微信openid'),
        ),
    ]
