# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-26 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='image',
        ),
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, help_text='文件', null=True, upload_to='allfiles/%Y/%m/%d/', verbose_name='文件'),
        ),
    ]
