# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-26 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0003_files_addtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='user',
            field=models.ForeignKey(blank=True, help_text='用户id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户id'),
        ),
    ]
