# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-24 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cates',
            name='image',
            field=models.ImageField(blank=True, help_text='图片', null=True, upload_to='cate/%Y/%m/%d/', verbose_name='图片'),
        ),
    ]
