# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-25 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cate', '0002_auto_20190224_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cates',
            options={'verbose_name': '案例栏目', 'verbose_name_plural': '案例栏目'},
        ),
    ]
