# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-25 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cate', '0003_auto_20190225_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cates',
            options={'verbose_name': '产品栏目', 'verbose_name_plural': '产品栏目'},
        ),
        migrations.RenameField(
            model_name='cates',
            old_name='cate',
            new_name='cate',
        ),
    ]
