# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 16:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resoucedit', '0006_auto_20190304_1407'),
        ('case', '0006_auto_20190306_1546'),
        ('cate', '0004_auto_20190225_1524'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activitys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='标题', max_length=255, verbose_name='标题')),
                ('image', models.ImageField(help_text='单张图', upload_to='actimage/%Y/%m/%d/', verbose_name='单张图')),
                ('start', models.DateTimeField(blank=True, help_text='开始时间', null=True, verbose_name='开始时间')),
                ('end', models.DateTimeField(blank=True, help_text='结束时间', null=True, verbose_name='结束时间')),
                ('reward_info', models.TextField(default='', help_text='奖品说明', verbose_name='奖品说明')),
                ('act_info', models.TextField(default='', help_text='活动说明', verbose_name='活动说明')),
                ('dui_info', models.TextField(default='', help_text='兑奖信息', verbose_name='兑奖信息')),
                ('intro', models.TextField(default='', help_text='机构介绍', verbose_name='机构介绍')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('attrs', models.ManyToManyField(help_text='属性列表', to='resoucedit.CaseAttrs', verbose_name='属性列表')),
                ('brands', models.ManyToManyField(help_text='门店列表', to='case.CaseBrands', verbose_name='门店列表')),
                ('case', models.ForeignKey(default='', help_text='案例id', on_delete=django.db.models.deletion.CASCADE, related_name='re_case', to='case.Acts', verbose_name='案例id')),
                ('cate', models.ForeignKey(blank=True, help_text='分类id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_cate_act', to='cate.Cates', verbose_name='分类id')),
                ('effect', models.ForeignKey(blank=True, help_text='特效id', null=True, on_delete=django.db.models.deletion.CASCADE, to='resoucedit.Effects', verbose_name='特效id')),
                ('favo', models.ManyToManyField(help_text='优惠列表', to='case.CaseFavo', verbose_name='优惠列表')),
                ('music', models.ForeignKey(blank=True, help_text='音乐id', null=True, on_delete=django.db.models.deletion.CASCADE, to='resoucedit.Music', verbose_name='音乐id')),
                ('signs', models.ManyToManyField(help_text='报名列表', to='case.CaseSigns', verbose_name='报名列表')),
                ('user', models.ForeignKey(help_text='用户id', on_delete=django.db.models.deletion.CASCADE, related_name='re_user', to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
            },
        ),
    ]
