# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-07 15:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeact', '0002_auto_20190307_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActBrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='名称', max_length=255, verbose_name='名称')),
                ('location_x', models.FloatField(default='', help_text='经度', verbose_name='经度')),
                ('location_y', models.FloatField(default='', help_text='纬度', verbose_name='纬度')),
                ('address', models.CharField(default='', help_text='具体地址', max_length=255, verbose_name='具体地址')),
                ('phones', models.CharField(default='', help_text='手机号组', max_length=255, verbose_name='手机号组')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('act', models.ForeignKey(help_text='活动id', on_delete=django.db.models.deletion.CASCADE, related_name='re_act_brands', to='makeact.Activitys', verbose_name='活动id')),
            ],
            options={
                'verbose_name': '活动门店',
                'verbose_name_plural': '活动门店',
            },
        ),
        migrations.CreateModel(
            name='ActFavo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='名称', max_length=255, verbose_name='名称')),
                ('sort', models.IntegerField(default=1, help_text='排序', verbose_name='排序')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('act', models.ForeignKey(help_text='活动id', on_delete=django.db.models.deletion.CASCADE, related_name='re_act', to='makeact.Activitys', verbose_name='活动id')),
            ],
            options={
                'verbose_name': '活动优惠',
                'verbose_name_plural': '活动优惠',
            },
        ),
        migrations.CreateModel(
            name='ActSigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='名称', max_length=255, verbose_name='名称')),
                ('value', models.CharField(default='', help_text='值', max_length=255, verbose_name='值')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('act', models.ForeignKey(blank=True, help_text='活动id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_act_signs', to='makeact.Activitys', verbose_name='活动id')),
            ],
            options={
                'verbose_name': '活动报名',
                'verbose_name_plural': '活动报名',
            },
        ),
    ]
