# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-24 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='名称', max_length=255, verbose_name='名称')),
                ('desc', models.TextField(default='', help_text='类别描述', verbose_name='类别描述')),
                ('type', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], help_text='类目级别', verbose_name='类目级别')),
                ('image', models.ImageField(blank=True, help_text='图片', null=True, upload_to='cate/', verbose_name='图片')),
                ('is_tab', models.BooleanField(default=False, help_text='是否导航', verbose_name='是否导航')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('cate', models.ForeignKey(blank=True, help_text='上级id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='brand.BrandCate', verbose_name='上级id')),
            ],
            options={
                'verbose_name': '店铺分类',
                'verbose_name_plural': '店铺分类',
            },
        ),
    ]
