# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-24 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_auto_20190224_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间'),
        ),
    ]
