# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-24 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_brand_addtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='banner',
            field=models.ImageField(blank=True, help_text='轮播图', null=True, upload_to='banner/%Y/%m/%d/', verbose_name='轮播图'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='code',
            field=models.ImageField(blank=True, help_text='二维码图片', null=True, upload_to='code/%Y/%m/%d/', verbose_name='二维码图片'),
        ),
        migrations.AlterField(
            model_name='brandcate',
            name='image',
            field=models.ImageField(blank=True, help_text='图片', null=True, upload_to='cate/%Y/%m/%d/', verbose_name='图片'),
        ),
    ]
