# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-25 14:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_auto_20190224_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCateImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='名称', max_length=255, verbose_name='名称')),
                ('image', models.ImageField(help_text='描述', upload_to='brandimage/%Y/%m/%d/', verbose_name='描述')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '行业图片',
                'verbose_name_plural': '行业图片',
            },
        ),
        migrations.CreateModel(
            name='BrandCateTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='名称', max_length=255, verbose_name='名称')),
                ('desc', models.CharField(default='', help_text='描述', max_length=255, verbose_name='描述')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '行业标题',
                'verbose_name_plural': '行业标题',
            },
        ),
        migrations.AlterModelOptions(
            name='brandcate',
            options={'verbose_name': '行业分类', 'verbose_name_plural': '行业分类'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='user',
            field=models.ForeignKey(blank=True, help_text='用户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sub', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='brandcatetitle',
            name='cate',
            field=models.ForeignKey(blank=True, help_text='分类id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_titles', to='brand.BrandCate', verbose_name='分类id'),
        ),
        migrations.AddField(
            model_name='brandcateimages',
            name='cate',
            field=models.ForeignKey(blank=True, help_text='分类id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_images', to='brand.BrandCate', verbose_name='分类id'),
        ),
    ]
