# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-25 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0006_auto_20190225_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='cate',
        ),
        migrations.RemoveField(
            model_name='brandcate',
            name='cate',
        ),
        migrations.RemoveField(
            model_name='brandcateimages',
            name='cate',
        ),
        migrations.RemoveField(
            model_name='brandcatetitle',
            name='cate',
        ),
        migrations.AddField(
            model_name='brand',
            name='cate',
            field=models.ForeignKey(blank=True, help_text='分类id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_sub', to='brand.BrandCate', verbose_name='分类id'),
        ),
        migrations.AddField(
            model_name='brandcate',
            name='cate',
            field=models.ForeignKey(blank=True, help_text='上级id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='brand.BrandCate', verbose_name='上级id'),
        ),
        migrations.AddField(
            model_name='brandcateimages',
            name='cate',
            field=models.ForeignKey(blank=True, help_text='分类id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_images', to='brand.BrandCate', verbose_name='分类id'),
        ),
        migrations.AddField(
            model_name='brandcatetitle',
            name='cate',
            field=models.ForeignKey(blank=True, help_text='分类id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_titles', to='brand.BrandCate', verbose_name='分类id'),
        ),
    ]
