# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-27 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0009_auto_20190226_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandcatetitle',
            name='cate',
        ),
        migrations.DeleteModel(
            name='BrandCateTitle',
        ),
    ]
